##########
### !!! - DO NOT CHANGE ANYTHING IN THIS FILE - !!!
##########

services:
  # BEGIN GATEWAY
  gateway:
    devices:
      - /dev/sgx:/dev/sgx
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.lifecycle.pre-update: "sleep $((74 + RANDOM % 46))" # minimum 74s - max 120s
      com.centurylinklabs.watchtower.lifecycle.pre-update-timeout: "121" # default is 120s
    logging:
      driver: "local"
      options:
        max-size: "16g"
    environment:
      ENABLE_PULL_ORACLE: "0"
      ENABLE_PUSH_ORACLE: "0"
      ENABLE_PUSH_MODEL: "false"
      ENABLE_GUARDIAN: "0"
      ENABLE_GATEWAY: "1"
    privileged: true
    stdin_open: true
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 1000000
  # END GATEWAY
