##########
### !!! - DO NOT CHANGE ANYTHING IN THIS FILE - !!!
##########

services:
  # BEGIN GUARDIAN
  guardian:
    image: ${DOCKER_IMAGE}
    devices:
      - /dev/sgx:/dev/sgx
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "16g"
    env_file:
      - ../../../cfg/00-common-vars.cfg
    environment:
      ENABLE_PULL_ORACLE: "0"
      ENABLE_PUSH_ORACLE: "0"
      ENABLE_PUSH_MODEL: "false"
      ENABLE_GUARDIAN: "1"
      ENABLE_GATEWAY: "0"
    privileged: true
    stdin_open: true
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 60000
  # END GUARDIAN
