##########
### !!! - DO NOT CHANGE ANYTHING IN THIS FILE - !!!
##########

services:
  # BEGIN ORACLE
  oracle:
    devices:
      - /dev/sgx:/dev/sgx
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "16g"
    environment:
      ENABLE_PULL_ORACLE: "1"
      ENABLE_PUSH_ORACLE: "0"
      ENABLE_PUSH_MODEL: "false"
      ENABLE_GUARDIAN: "0"
      ENABLE_GATEWAY: "0"
    privileged: true
    stdin_open: true
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 1000000
  # END ORACLE
