services:
  # BEGIN SHARED VMAGENT
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.101.0
    #ports:
    #  # HTTP
    #  - target: 8429
    #    published: 8429
    #    protocol: tcp
    command:
      - "--promscrape.config=/etc/prometheus/cfg-vmagent.yml"
      - "--remoteWrite.url=https://remote-write.switchboard.xyz/api/v1/write"
      - "--loggerLevel=ERROR"
    restart: unless-stopped
    env_file:
      - ../../../cfg/00-common-vars.cfg
    logging:
      driver: "local"
      options:
        max-size: "64g"
  # END SHARED VMAGENT
