services:
  # BEGIN SHARED WATCHTOWER
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --enable-lifecycle-hooks # --enable-lifecycle-hooks Enable the execution of commands triggered by pre- and post-update lifecycle hooks
      - --label-enable           # -e, --label-enable       Watch containers where the com.centurylinklabs.watchtower.enable label is true
      - --cleanup                # -c, --cleanup            Remove previously used images after updating
      - --include-restarting     #     --include-restarting Will also include restarting containers
      - --rolling-restart
      - --interval               # -i, --interval int       Poll interval (in seconds) (default 86400)
      - "30"

      # list of containers to monitor for changes
      - devnet-oracle
      - devnet-guardian
      - devnet-gateway
      - devnet-vmagent

      - mainnet-oracle
      - mainnet-guardian
      - mainnet-gateway
      - mainnet-vmagent

      - v2-vmagent
      - v2-oracle

      - switchboard-webserver
  # END SHARED WATCHTOWER

# OTHER USEFUL OPTIONS FROM watchtower
# -n, --notifications strings                       Notification types to send (valid: email, slack, msteams, gotify, shoutrrr)
#     --notifications-hostname string               Custom hostname for notification titles

#     --notification-slack-channel string           A string which overrides the webhook's default channel. Example: #my-custom-channel
#     --notification-slack-hook-url string          The Slack Hook URL to send notifications to
#     --notification-slack-icon-emoji string        An emoji code string to use in place of the default icon
#     --notification-slack-icon-url string          An icon image URL string to use in place of the default icon
#     --notification-slack-identifier string        A string which will be used to identify the messages coming from this watchtower instance (default "watchtower")

#     --notification-email-delay int                Delay before sending notifications, expressed in seconds
#     --notification-email-from string              Address to send notification emails from
#     --notification-email-server string            SMTP server to send notification emails through
#     --notification-email-server-password string   SMTP server password for sending notifications
#     --notification-email-server-port int          SMTP server port to send notification emails through (default 25)
#     --notification-email-server-tls-skip-verify   Controls whether watchtower verifies the SMTP server's certificate chain and host name.
#     --notification-email-server-user string       SMTP server user for sending notifications
#     --notification-email-subjecttag string        Subject prefix tag for notifications via mail
#     --notification-email-to string                Address to send notification emails to

# -x, --disable-containers strings                  Comma-separated list of containers to explicitly exclude from watching.
# -S, --include-stopped                             Will also include created and exited containers
# -m, --monitor-only                                Will only monitor for new images, not update the containers
#     --remove-volumes                              Remove attached volumes before updating

# -s, --schedule string                             The cron expression which defines when to update
