services:
  # BEGIN SHARED MAIN WEBSERVER
  webserver:
    image: caddy:2
    container_name: switchboard-webserver
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTPS/3
      - target: 443
        published: 443
        protocol: udp
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.lifecycle.pre-update: "sleep $((74 + RANDOM % 46))" # minimum 74s - max 120s
      com.centurylinklabs.watchtower.lifecycle.pre-update-timeout: "121" # default is 120s
    networks:
      - devnet
      - mainnet
    env_file:
      - ../../../cfg/00-common-vars.cfg
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../data/caddy-data:/data
      - ../data/caddy-config:/config
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "64g"
  # END SHARED MAIN WEBSERVER
