networks:
  mainnet:
  devnet:

services:
  # BEGIN SHARED MAIN WEBSERVER
  webserver:
    image: caddy
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTPS/3
      - target: 443
        published: 443
        protocol: udp
    networks:
      - devnet
      - mainnet
    env_file:
      - ../../../cfg/00-vars.cfg
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../data/caddy-data:/data
      - ../data/caddy-config:/config
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "64g"
  # END SHARED MAIN WEBSERVER
