
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oracle-updater
  namespace: {{ $.Values.oracle_updater.namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oracle-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oracle-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oracle-updater
subjects:
- kind: ServiceAccount
  name: oracle-updater
  namespace: {{ $.Values.oracle_updater.namespace | quote }}

