apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ $.Values.gateway.port }}
      targetPort: {{ $.Values.gateway.port }}
