{{- range $component, $config := .Values.oracle }}
{{- if or (eq $component "guardian") (eq $component "push") (eq $component "pull") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $component }}-oracle-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $component }}-oracle
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
---
{{- end }}          
{{- end }}                
