apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: oracle
  ports:
    - protocol: TCP
      port: {{ $.Values.oracle.port }}
      targetPort: {{ $.Values.oracle.port }}
