{{- range $component, $config := .Values.oracle }}
{{- if or (eq $component "guardian") (eq $component "push") (eq $component "pull") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $component }}-oracle-ingress
  namespace: {{ $.Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ $config.host }}
    secretName: {{ $component }}-oracle-cert-manager-tls
  rules:
  - host: {{ $config.host }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ $component }}-oracle-service
            port:
              number: {{ $config.port }}
        pathType: ImplementationSpecific
---
{{- end }}
{{- end }}
