{{- range $component, $config := .Values.components }}
{{- if or (eq $component "guardian") (eq $component "gateway") (eq $component "oracle") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $component }}-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $component }}-oracle
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
      name: {{ $component }}-svc
---
{{- end }}
{{- end }}
