chain: ""
cluster: ""
networkId: ""
namespace: "default"
host: ""

computeUnitLimit: 300000
computeUnitPrice: 1

heartbeatInterval: 180

payerSecret: ""
payerSecretKey: ""

rpcUrl: ""
wssRpcUrl: ""
solanaMainnetRpc: ""

jupiterSwapApiKey: ""

debug: ""
verbose: ""
list_config_and_exit: ""

components:
  docker_image_tag: "devnet"

  oracle:
    enabled: true
    image: "docker.io/switchboardlabs/oracle"
    queue: ""
    key: ""
    port: 8081
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "4000m"
        memory: "2000Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"

  guardian:
    enabled: true
    image: "docker.io/switchboardlabs/guardian"
    queue: ""
    key: ""
    port: 8083
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "4000m"
        memory: "2000Mi"
      requests:
        cpu: "200m"
        memory: "100Mi"

  gateway:
    enabled: true
    image: "docker.io/switchboardlabs/gateway"
    port: 8082
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "4000m"
        memory: "1000Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"

