chain: ""
cluster: ""
networkId: ""
namespace: "default"

computeUnitLimit: ""
computeUnitPrice: ""
heartbeatInterval: ""

payerSecret: ""
payerSecretKey: ""
infisical:
  secret:
    key: ""
    path: ""
    slug: ""
  token:
    namespace: ""

rpcUrl: ""
solanaMainnetRpc: ""

debug: ""
verbose: ""

components:

    oracle:
      image: "docker.io/switchboardlabs/oracle:stable"
      queue: ""
      key: ""
      host: ""
      port: 8081
      ingress: ""
      command: ""
      metrics:
        exporter: "prometheus"
        port: 9090
        path: "/metrics"
      resources:
        limits:
          cpu: "3000m"
          memory: "8000Mi"
          sgx:
            epc: "64Mi"
            enclave: 1
            provision: 1
        requests:
          cpu: "1500m"
          memory: "4000Mi"
          sgx:
            epc: "64Mi"
            enclave: 1
            provision: 1

    guardian:
      image: "docker.io/switchboardlabs/guardian:stable"
      queue: ""
      key: ""
      host: ""
      port: 8083
      ingress: ""
      command: ""
      metrics:
        exporter: "prometheus"
        port: 9090
        path: "/metrics"
      resources:
        limits:
          cpu: "3000m"
          memory: "8000Mi"
          sgx:
            epc: "64Mi"
            enclave: 1
            provision: 1
        requests:
          cpu: "1500m"
          memory: "4000Mi"
          sgx:
            epc: "64Mi"
            enclave: 1
            provision: 1

    gateway:
      image: "docker.io/switchboardlabs/gateway:stable"
      host: ""
      port: 8082
      ingress: ""
      command: ""
      metrics:
        exporter: "prometheus"
        port: 9090
        path: "/metrics"
      resources:
        limits:
          cpu: "3000m"
          memory: "8000Mi"
          sgx:
            epc: "64Mi"
            enclave: 1
            provision: 1
        requests:
          cpu: "1500m"
          memory: "4000Mi"
          sgx:
            epc: "64Mi"
            enclave: 1
            provision: 1



### OLD STUFF

attestationProgramId: ""

azureSecretName: ""
azureSecretPath: ""
azureVaultUrl: ""

dockerKey: ""
dockerUser: ""
evmChainId: ""
feedRelayerEnabled: ""
gcpConfigBucket: ""

googleApplicationCredentials: ""
googlePayerSecretPath: ""


host: "x.y.z"


ipfsApiUrl: "ipfs.infura.io"
ipfsKey: ""
ipfsSecret: ""
ipfsUrl: "https://ipfs.infura.io:5001"




pushModel: "true"
pvcName: "function-manager-pvc"

saveResultComputeUnits: 300000

serviceAccountJson: "bnVsbA==" #base64 encoded json
serviceAccountName: ""


appType: "oracle"
azureClientID: ""
azureTenantID: ""

sgx:
  type: ""
  memoryMiB: 0
  cpu: 0

txTelemetry:
  pgHost: ""
  pgUser: ""
  pgDatabase: ""
  pgPassword: ""

influxdbEndpoint: "remote-write.switchboard.xyz/write"

ingress:
  enabled: false

oracleKeys:
  - name: idx-1
    data: ""
    queue: ""
    queueAddress: ""
    payerSecret: ""
    oracleQueueKey: ""
    oracleAuthority: ""
    solanaOracleQueueKey: ""
    sasQueue: ""
    dockerUser: ""
    dockerKey: ""
    ipfsUrl: "https://ipfs.infura.io:5001"
    ipfsKey: "XXX"
    ipfsSecret: "XXX"
    attestationQueue: ""
