chain: ""
cluster: ""
networkId: ""
namespace: "default"
host: ""

computeUnitLimit: 300000
computeUnitPrice: 1

heartbeatInterval: 180

payerSecret: ""
payerSecretKey: ""

sgx_sealed_files: "/data/protected_files"

rpcUrl: ""
wssRpcUrl: ""
solanaMainnetRpc: ""

jupiterSwapApiKey: ""

debug: ""
verbose: ""
list_config_and_exit: ""

components:
  docker_image_tag: "devnet"

  oracle:
    enabled: true
    image: "docker.io/switchboardlabs/oracle"
    queue: ""
    key: ""
    port: 8081
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-prod-http"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "3000m"
        memory: "8000Mi"
        sgx:
          epc: "64Mi"
          enclave: 1
          provision: 1
      requests:
        cpu: "1500m"
        memory: "4000Mi"
        sgx:
          epc: "64Mi"
          enclave: 1
          provision: 1

  guardian:
    enabled: true
    image: "docker.io/switchboardlabs/guardian"
    queue: ""
    key: ""
    port: 8083
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-prod-http"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "3000m"
        memory: "8000Mi"
        sgx:
          epc: "64Mi"
          enclave: 1
          provision: 1
      requests:
        cpu: "1500m"
        memory: "4000Mi"
        sgx:
          epc: "64Mi"
          enclave: 1
          provision: 1

  gateway:
    enabled: true
    image: "docker.io/switchboardlabs/gateway"
    port: 8082
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-prod-http"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "3000m"
        memory: "8000Mi"
        sgx:
          epc: "64Mi"
          enclave: 1
          provision: 1
      requests:
        cpu: "1500m"
        memory: "4000Mi"
        sgx:
          epc: "64Mi"
          enclave: 1
          provision: 1
