chain: ""
cluster: ""
networkId: ""
namespace: "default"
host: ""

computeUnitLimit: 300000
computeUnitPrice: 1

heartbeatInterval: 180

payerSecret: ""
payerSecretKey: ""

rpcUrl: ""
wssRpcUrl: ""
solanaMainnetRpc: ""

jupiterSwapApiKey: ""

debug: ""
verbose: ""
list_config_and_exit: ""

components:
  docker_image_tag: "devnet"

  oracle:
    enabled: true
    image: "docker.io/switchboardlabs/oracle"
    queue: ""
    key: ""
    port: 8081
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "4000m"
        memory: "2000Mi"
      requests:
        cpu: "1000m"
        memory: "500Mi"

  guardian:
    enabled: true
    image: "docker.io/switchboardlabs/guardian"
    queue: ""
    key: ""
    port: 8083
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "4000m"
        memory: "2000Mi"
      requests:
        cpu: "2000m"
        memory: "1000Mi"

  gateway:
    enabled: true
    image: "docker.io/switchboardlabs/gateway"
    port: 8082
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    metrics:
      exporter: "prometheus"
      endpoint: "remote-write.switchboard.xyz/write"
      port: 9090
      path: "/metrics"
    resources:
      limits:
        cpu: "4000m"
        memory: "1000Mi"
      requests:
        cpu: "500m"
        memory: "500Mi"

  landing:
    enabled: true
    image: "docker.io/switchboardlabs/reporteer"
    image_tag: "latest"
    port: 3000
    attestation_url: "http://127.0.0.1:8006/derived_key"
    ingress:
      enabled: true
      class: "nginx"
      issuer: "letsencrypt-production"
      url: ""
    command: ""
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

