apiVersion: v2
name: switchboard-monitoring
description: A Helm chart for the Switchboard monitoring stack

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

dependencies:
- name: victoria-metrics-agent
  version: "0.15.8"
  repository: "https://victoriametrics.github.io/helm-charts/"
- name: kube-state-metrics
  version: "5.30.0"
  repository: "https://prometheus-community.github.io/helm-charts"

icon: "https://raw.githubusercontent.com/switchboard-xyz/switchboard/main/website/static/img/icons/switchboard/avatar.png"
