{
 "title": "switchboard metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "last crankpop (unix time)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(switchboard_last_crankpop_unix_time[${__range_s}s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last tx (unix time)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(switchboard_last_tx_unix_time[${__range_s}s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(count_values(\"oraclePubkey\",switchboard_oracle_version_total[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feed Variance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, max(switchboard_aggregator_variances[1m]) by (feedName))"
    }
   ]
  },
  {
   "title": "Round Age",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,max(switchboard_round_age[${__range_s}s]) by (feedName))"
    }
   ]
  },
  {
   "title": "save result failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (errorType) (rate(switchboard_save_result_failure_total[5m]))"
    }
   ]
  },
  {
   "title": "insufficient aggregation error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster,pod) (rate(switchboard_node_aggregation_insufficient_responses_total[5m]))"
    }
   ]
  }
 ]
}