{
 "title": "Triage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "feed_name",
    "query": "2oALNZVi5czyHvKbnjE4Jf2gR7dNp1FBpEGaq4PzVAf7"
   },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Round Age 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(quantile_over_time(0.95, switchboard_round_age{feedName=\"$feed_name\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(max_over_time(switchboard_round_age{feedName=\"$feed_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "aggregator variance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(switchboard_aggregator_variances{feedName=\"$feed_name\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}