apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-sample
  namespace: default
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: dev
        secretsPath: /
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
  hostAPI: https://app.infisical.com/api
  managedSecretReference:
    secretName: infisical-secret
    secretNamespace: default
  resyncInterval: 60
