loki:
#  extraArgs:
#    - "-log.level=debug"
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
gateway:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"  # replace with your issuer name
    path: /
    hosts:
      - loki-gateway.domain.com
    tls:
      - secretName: loki-gateway-tls  # replace with your secret name
        hosts:
          - loki-gateway.domain.com


#  table_manager:
#    retention_deletes_enabled: false
#    retention_period: 0s

# helm upgrade --install loki grafana/loki -f loki.yaml 



