server:
  enabled: true
  statefulSet:
    enabled: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "issuer-name"  # replace with your issuer name
    path: /
    hosts:
      - victoria-metrics.domain.com
    tls:
      - secretName: victoria-metrics-tls  # replace with your secret name
        hosts:
          - victoria-metrics.domain.com
  scrape:
    enabled: true
    configMap: ""
    config:
      global:
        scrape_interval: 60s 
      scrape_configs:
        - job_name: "switchboard-pods"
          kubernetes_sd_configs:
            - role: pod
          scheme: http
          metrics_path: /metrics
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_should_scrape]
              regex: scrape
              action: keep
        - job_name: "version-pods"
          kubernetes_sd_configs:
            - role: pod
          scheme: http
          metrics_path: /metrics
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: version-metric
              action: keep

