server:
  enabled: true
  statefulSet:
    enabled: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    path: /
    hosts:
      - "_SET_VIA_ENV_"
    tls:
      - secretName: victoria-metrics-tls
        hosts:
          - "_SET_VIA_ENV_"
  scrape:
    enabled: true
    configMap: ""
    config:
      global:
        scrape_interval: 60s
      scrape_configs:
        - job_name: "switchboard-pods"
          kubernetes_sd_configs:
            - role: pod
          scheme: http
          metrics_path: /metrics
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_should_scrape]
              regex: scrape
              action: keep
        - job_name: "version-pods"
          kubernetes_sd_configs:
            - role: pod
          scheme: http
          metrics_path: /metrics
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: version-metric
              action: keep

