##########
### !!! - DO NOT CHANGE ANYTHING IN THIS FILE - !!!
##########

include:
  - ../common/webserver.yml

services:
  # BEGIN ORACLE
  mainnet-oracle:
    extends:
      file: ../common/oracle.yml
      service: oracle
    volumes:
      - ../data/mainnet_protected_files/:/data/protected_files/
    networks:
      - mainnet
    env_file:
      - ./00-vars.env
      - ./payer-secret.env
      - ./common.env
  # END ORACLE

  # BEGIN GUARDIAN
  mainnet-guardian:
    extends:
      file: ../common/guardian.yml
      service: guardian
    volumes:
      - ../data/mainnet_protected_files/:/data/protected_files/
    networks:
      - mainnet
    env_file:
      - ./00-vars.env
      - ./payer-secret.env
      - ./common.env
  # END GUARDIAN

  # BEGIN GATEWAY
  mainnet-gateway:
    extends:
      file: ../common/gateway.yml
      service: gateway
    volumes:
      - ../data/mainnet_protected_files/:/data/protected_files/
    networks:
      - mainnet
    env_file:
      - ./00-vars.env
      - ./payer-secret.env
      - ./common.env
  # END GATEWAY
