global:
  scrape_interval: 60s
  scrape_timeout: 20s

scrape_configs:
  - job_name: "switchboard-pull-oracle"

    static_configs:
      - targets:
        - "devnet-oracle:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - action: labelmap_all
      regex: '"'
      replacement: ''

    - action: replace_all
      regex: "^\""
      replacement: ""
    - action: replace_all
      regex: "\"$"
      replacement: ""
    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: pull_oracle
      replacement: "%{PULL_ORACLE}"
    - target_label: pull_queue
      replacement: "%{PULL_QUEUE}"

  - job_name: "switchboard-pull-guardian"

    static_configs:
      - targets:
        - "devnet-guardian:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - action: labelmap_all
      regex: '"'
      replacement: ''

    - action: replace_all
      regex: "^\""
      replacement: ""
    - action: replace_all
      regex: "\"$"
      replacement: ""
    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: guardian_oracle
      replacement: "%{GUARDIAN_ORACLE}"
    - target_label: guardian_queue
      replacement: "%{GUARDIAN_QUEUE}"

  - job_name: "switchboard-pull-gateway"

    static_configs:
      - targets:
        - "devnet-gateway:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - action: labelmap_all
      regex: '"'
      replacement: ''

    - action: replace_all
      regex: "^\""
      replacement: ""
    - action: replace_all
      regex: "\"$"
      replacement: ""

    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: pull_oracle
      replacement: "%{PULL_ORACLE}"
    - target_label: pull_queue
      replacement: "%{PULL_QUEUE}"
    - target_label: guardian_oracle
      replacement: "%{GUARDIAN_ORACLE}"
    - target_label: guardian_queue
      replacement: "%{GUARDIAN_QUEUE}"
