global:
  scrape_interval: 60s
  scrape_timeout: 20s

scrape_configs:
  - job_name: "switchboard-pull-oracle"

    static_configs:
      - targets:
        - "devnet-oracle:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - target_label: platform
      replacement: "docker-compose"
    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: pull_oracle
      replacement: "%{PULL_ORACLE}"
    - target_label: pull_queue
      replacement: "%{PULL_QUEUE}"
    - source_labels: [operator]
      target_label: operator
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [cluster]
      target_label: cluster
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [pull_oracle]
      target_label: pull_oracle
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [pull_queue]
      target_label: pull_queue
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [job]
      target_label: job
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [instance]
      target_label: instance
      action: replace_all
      regex: '"'
      replacement: ''

  - job_name: "switchboard-pull-guardian"

    static_configs:
      - targets:
        - "devnet-guardian:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - target_label: platform
      replacement: "docker-compose"
    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: guardian_oracle
      replacement: "%{GUARDIAN_ORACLE}"
    - target_label: guardian_queue
      replacement: "%{GUARDIAN_QUEUE}"
    - source_labels: [operator]
      target_label: operator
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [cluster]
      target_label: cluster
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [guardian_oracle]
      target_label: guardian_oracle
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [guardian_queue]
      target_label: guardian_queue
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [job]
      target_label: job
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [instance]
      target_label: instance
      action: replace_all
      regex: '"'
      replacement: ''

  - job_name: "switchboard-pull-gateway"

    static_configs:
      - targets:
        - "devnet-gateway:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - target_label: platform
      replacement: "docker-compose"
    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: pull_oracle
      replacement: "%{PULL_ORACLE}"
    - target_label: pull_queue
      replacement: "%{PULL_QUEUE}"
    - target_label: guardian_oracle
      replacement: "%{GUARDIAN_ORACLE}"
    - target_label: guardian_queue
      replacement: "%{GUARDIAN_QUEUE}"
    - source_labels: [operator]
      target_label: operator
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [cluster]
      target_label: cluster
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [pull_oracle]
      target_label: pull_oracle
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [pull_queue]
      target_label: pull_queue
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [guardian_oracle]
      target_label: guardian_oracle
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [guardian_queue]
      target_label: guardian_queue
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [job]
      target_label: job
      action: replace_all
      regex: '"'
      replacement: ''
    - source_labels: [instance]
      target_label: instance
      action: replace_all
      regex: '"'
      replacement: ''
