##########
### !!! - DO NOT CHANGE ANYTHING IN THIS FILE - !!!
##########

secrets:
  devnet_payer_secret:
    file: ../../../data/devnet_payer.json

services:
  # BEGIN ORACLE
  devnet-oracle:
    extends:
      file: ../common/oracle.yml
      service: oracle
    volumes:
      - ../../../data/devnet_protected_files/:/data/protected_files/
    networks:
      - devnet
    environment:
      PAYER_SECRET_FILEPATH: /run/secrets/devnet_payer_secret
    secrets:
      - devnet_payer_secret
    env_file:
      - ../../../cfg/00-devnet-vars.cfg
      - ../common/devnet.env
  # END ORACLE

  # BEGIN GUARDIAN
  devnet-guardian:
    extends:
      file: ../common/guardian.yml
      service: guardian
    volumes:
      - ../../../data/devnet_protected_files/:/data/protected_files/
    networks:
      - devnet
    environment:
      PAYER_SECRET_FILEPATH: /run/secrets/devnet_payer_secret
    secrets:
      - devnet_payer_secret
    env_file:
      - ../../../cfg/00-devnet-vars.cfg
      - ../common/devnet.env
  # END GUARDIAN

  # BEGIN GATEWAY
  devnet-gateway:
    extends:
      file: ../common/gateway.yml
      service: gateway
    volumes:
      - ../../../data/devnet_protected_files/:/data/protected_files/
    networks:
      - devnet
    environment:
      PAYER_SECRET_FILEPATH: /run/secrets/devnet_payer_secret
    secrets:
      - devnet_payer_secret
    env_file:
      - ../../../cfg/00-devnet-vars.cfg
      - ../common/devnet.env
  # END GATEWAY

  # BEGIN WEBSERVER
  webserver:
    extends:
      file: ../common/guardian.yml
      service: webserver
    env_file:
      - ../../../cfg/00-devnet-vars.cfg
  # END WEBSERVER
