{{- $oracleEnabled := and $.Values.components.oracle.enabled $.Values.components.oracle.ingress.enabled }}
{{- $gatewayEnabled := and $.Values.components.gateway.enabled $.Values.components.gateway.ingress.enabled }}
{{- $guardianEnabled := and $.Values.components.guardian.enabled $.Values.components.guardian.ingress.enabled }}
{{- if or $oracleEnabled $gatewayEnabled $guardianEnabled }}
{{- $rewrites := list }}
{{- if $oracleEnabled }}{{- $rewrites = append $rewrites "serviceName=oracle rewrite=/oracle" }}{{- end }}
{{- if $gatewayEnabled }}{{- $rewrites = append $rewrites "serviceName=gateway rewrite=/gateway" }}{{- end }}
{{- if $guardianEnabled }}{{- $rewrites = append $rewrites "serviceName=guardian rewrite=/guardian" }}{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: on-demand
  namespace: {{ $.Values.namespace | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ coalesce $.Values.components.oracle.ingress.issuer $.Values.components.gateway.ingress.issuer $.Values.components.guardian.ingress.issuer | quote }}
    nginx.org/rewrites: {{ join ";" $rewrites | quote }}
spec:
  ingressClassName: {{ coalesce $.Values.components.oracle.ingress.class $.Values.components.gateway.ingress.class $.Values.components.guardian.ingress.class | quote }}
  tls:
  - hosts:
    - {{ $.Values.host | quote }}
    secretName: ingress-tls
  rules:
  - host: {{ $.Values.host | quote }}
    http:
      paths:
      {{- if $oracleEnabled }}
      - path: /{{ $.Values.cluster }}/oracle
        pathType: Prefix
        backend:
          service:
            name: oracle
            port:
              number: {{ $.Values.components.oracle.port }}
      {{- end }}
      {{- if $gatewayEnabled }}
      - path: /{{ $.Values.cluster }}/gateway
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: {{ $.Values.components.gateway.port }}
      {{- end }}
      {{- if $guardianEnabled }}
      - path: /{{ $.Values.cluster }}/guardian
        pathType: Prefix
        backend:
          service:
            name: guardian
            port:
              number: {{ $.Values.components.guardian.port }}
      {{- end }}
{{- end }}
