##########
### !!! - DO NOT CHANGE ANYTHING IN THIS FILE - !!!
##########

include:
  - ../common/networks.yml

secrets:
  deprecated_v2_payer_secret:
    file: ../../../data/deprecated_v2_payer.json

services:
  # BEGIN ORACLE
  v2-oracle:
    # dev-RC_06_30_24_23_12
    image: ${DOCKER_IMAGE:-docker.io/switchboardlabs/pull-oracle:v2-on-v3}
    container_name: v2-oracle
    volumes:
      - ../../../data/deprecated_v2_protected_files/:/data/protected_files/
    networks:
      - v2
    secrets:
      - deprecated_v2_payer_secret
    env_file:
      - ../../../cfg/00-common-vars.cfg
      - ./v2.env
      - ../../../cfg/00-deprecated-v2-vars.cfg
    devices:
      - /dev/sgx:/dev/sgx
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "16g"
    environment:
      ENABLE_PUSH_ORACLE: "1"
      ENABLE_PUSH_MODEL: "false"
      ENABLE_PULL_ORACLE: "0"
      ENABLE_GUARDIAN: "0"
      ENABLE_GATEWAY: "0"
      PAYER_SECRET_FILEPATH: /run/secrets/deprecated_v2_payer_secret
      PAYER_KEY: ""
      ORACLE_AUTHORITY: ""
    privileged: true
    stdin_open: true
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 1000000
  # END ORACLE

  # BEGIN VMAGENT
  v2-vmagent:
    extends:
      file: ../common/vmagent.yml
      service: vmagent
    container_name: v2-vmagent
    networks:
      - v2
    volumes:
      - ../../../data/v2-vmagent-data:/vmagentdata
      - ./v2-cfg-vmagent.yml:/etc/prometheus/cfg-vmagent.yml:ro
    env_file:
      - ../../../cfg/00-deprecated-v2-vars.cfg
  # END VMAGENT
