global:
  scrape_interval: 60s
  scrape_timeout: 20s

scrape_configs:
  - job_name: "switchboard-push-oracle"

    static_configs:
      - targets:
        - "mainnet-oracle:9090/metrics"

    metric_relabel_configs:
    - if: '{__name__=~"^switchboard_.*$|^up$"}'
      action: keep

    relabel_configs:
    - target_label: operator
      replacement: "%{CLUSTER_DOMAIN}"
    - target_label: cluster
      replacement: "%{NETWORK}"
    - target_label: push_oracle
      replacement: "%{PUSH_ORACLE}"
    - target_label: push_queue
      replacement: "%{PUSH_QUEUE}"
