debug: ""
verbose: ""
list_config_and_exit: ""

oracle:
  mainnet:
    enabled: false
  devnet:
    enabled: true

guardian:
  mainnet:
    enabled: false
  devnet:
    enabled: false

oracle_landing_page:
  image: "docker.io/switchboardlabs/oracle-landing-page"
  image_tag: "latest"
  namespace: "default"
  port: 80
  attestation_url: "http://127.0.0.1:8006/derived_key"
  ingress:
    enabled: true
    class: "nginx"
    issuer: "letsencrypt-production"
    host: ""
    url: ""
  command: ""
  resources:
    limits:
      cpu: "250m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
