{{ if $values.infisicalSecretKey }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret
  namespace: {{ $.Values.namespace }}
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: {{ $.Values.infisicalSecretSlug }}
        secretsPath: {{ $.Values.infisicalSecretPath }}
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: {{ $.Values.infisicalTokenNamespace }} 
  hostAPI: https://app.infisical.com/api
  managedSecretReference:
    secretName: infisical-secret
    secretNamespace: {{ $.Values.namespace }}
  resyncInterval: 60
  {{ end }}
