{{- $values := .Values -}}
{{ if eq $.Values.appType "dind" }}
{{- range $index, $key := .Values.oracleKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: dind-dotenv
  namespace: {{ $.Values.namespace }}

type: Opaque
stringData:
  .env: |  
    SOLANA_ORACLE_QUEUE_KEY={{ $key.oracleQueueKey }}
    CHAIN={{ $.Values.chain }}
    CLUSTER={{ $values.networkId }}
    GOOGLE_PAYER_SECRET_PATH={{ if $key.googlePayerSecretPath }}{{ $key.googlePayerSecretPath }}{{ else }}{{ $values.googlePayerSecretPath }}{{ end }}
    GOOGLE_APPLICATION_CREDENTIALS={{ $values.googleApplicationCredentials }}
    RPC_URL={{ if $key.rpcUrl }}{{ $key.rpcUrl }}{{ else }}{{ $values.rpcUrl }}{{ end }}
    QUEUE={{ $key.queueAddress  }}
    TASK_RUNNER_SOLANA_RPC={{ $values.solanaMainnetRpc | default "https://switchboard.rpcpool.com/ec20ad2831092cfcef66d677539a" }}
---
{{ end }}
{{ end }}
