{{ if eq $.Values.appType "dind" }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-sample
  namespace: {{ $.Values.namespace }}
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: {{ $.Values.infisicalSecretSlug }}
        secretsPath: /
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
  hostAPI: https://app.infisical.com/api
  managedSecretReference:
    secretName: infisical-secret
    secretNamespace: {{ $.Values.namespace }}
  resyncInterval: 60
{{ end }}
