{{ if eq $.Values.appType "dind" }}
{{- $values := .Values -}}
apiVersion: v1
kind: Service
metadata:
  name: qvn-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: qvn
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
{{ end }}
