{{ if .Values.sgx.type }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.appType}}-service-account
  namespace: {{ $.Values.namespace }}
data:
  gcp-sa.json: {{ .Values.serviceAccountJson }}
{{ end }}
