---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging-http
    cert-manager.io/issue-temporary-certificate: "true"
    kubernetes.io/ingress.class: nginx
  name: nginx
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: 141.95.35.110.xip.switchboard-oracles.xyz
    http:
      paths:
      - backend:
          service:
            name: reporteer
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - 141.95.35.110.xip.switchboard-oracles.xyz
    secretName: letsencrypt-prod-http
