---
apiVersion: v1
kind: Service
metadata:
  name: sail
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: sail
  ports:
  - port: {{ .Values.sail.service.port | default 80 }}
    targetPort: {{ .Values.sail.pod.port | default 3000 }}
    name: http
    protocol: TCP
