function load_vars() {
  local tmp_helm_file="${1}"
  sed -i 's;__EMAIL__;'"${EMAIL}"';g' "${tmp_helm_file}"
  sed -i 's;__IP4__;'"${IP4}"';g' "${tmp_helm_file}"
  sed -i 's;__IP6__;'"${IP6}"';g' "${tmp_helm_file}"
  sed -i 's;__PAYER_SECRET_KEY__;'"${PAYER_SECRET_KEY}"';g' "${tmp_helm_file}"
  sed -i 's;__INFISICAL_SECRET_KEY__;'"${INFISICAL_SECRET_KEY}"';g' "${tmp_helm_file}"
  sed -i 's;__INFISICAL_SECRET_PATH__;'"${INFISICAL_SECRET_PATH}"';g' "${tmp_helm_file}"
  sed -i 's;__INFISICAL_SECRET_SLUG__;'"${INFISICAL_SECRET_SLUG}"';g' "${tmp_helm_file}"
  sed -i 's;__INFISICAL_TOKEN_NS__;'"${INFISICAL_TOKEN_NS}"';g' "${tmp_helm_file}"
  sed -i 's;__NAMESPACE__;'"${NAMESPACE}"';g' "${tmp_helm_file}"
  sed -i 's;__NETWORK__;'"${NETWORK}"';g' "${tmp_helm_file}"
  sed -i 's;__CLUSTER_DOMAIN__;'"${CLUSTER_DOMAIN}"';g' "${tmp_helm_file}"
  sed -i 's;__PULL_ORACLE__;'"${PULL_ORACLE}"';g' "${tmp_helm_file}"
  sed -i 's;__PULL_QUEUE__;'"${PULL_QUEUE}"';g' "${tmp_helm_file}"
  sed -i 's;__GUARDIAN_QUEUE__;'"${GUARDIAN_QUEUE}"';g' "${tmp_helm_file}"
  sed -i 's;__GUARDIAN_ORACLE__;'"${GUARDIAN_ORACLE}"';g' "${tmp_helm_file}"
  sed -i 's;__RPC_URL__;'"${RPC_URL}"';g' "${tmp_helm_file}"
  sed -i 's;__WSS_URL__;'"${WSS_URL}"';g' "${tmp_helm_file}"
  sed -i 's;__DOCKER_IMAGE__;'"${DOCKER_IMAGE}"';g' "${tmp_helm_file}"
  sed -i 's;__GATEWAY_INGRESS__;'"${GATEWAY_INGRESS}"';g' "${tmp_helm_file}"
  sed -i 's;__GUARDIAN_INGRESS__;'"${GUARDIAN_INGRESS}"';g' "${tmp_helm_file}"
  sed -i 's;__ORACLE_INGRESS__;'"${ORACLE_INGRESS}"';g' "${tmp_helm_file}"
}
