function load_vars() {
  local tmp_helm_file="${1}"
  sed -E -i 's;(__|\$\{)EMAIL(\}|__);'"${EMAIL}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)IPv4(\}|__);'"${IPv4}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)IPv6(\}|__);'"${IPv6}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)PAYER_SECRET_KEY(\}|__);'"${PAYER_SECRET_KEY}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)INFISICAL_SECRET_KEY(\}|__);'"${INFISICAL_SECRET_KEY}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)INFISICAL_SECRET_PATH(\}|__);'"${INFISICAL_SECRET_PATH}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)INFISICAL_SECRET_SLUG(\}|__);'"${INFISICAL_SECRET_SLUG}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)INFISICAL_TOKEN_NS(\}|__);'"${INFISICAL_TOKEN_NS}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)NAMESPACE(\}|__);'"${NAMESPACE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)NETWORK(\}|__);'"${NETWORK}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)CLUSTER_DOMAIN(\}|__);'"${CLUSTER_DOMAIN}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)RPC_URL(\}|__);'"${RPC_URL}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)WSS_RPC_URL(\}|__);'"${WSS_RPC_URL}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)TASK_RUNNER_SOLANA_RPC(\}|__);'"${TASK_RUNNER_SOLANA_RPC}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)PULL_QUEUE(\}|__);'"${PULL_QUEUE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)PULL_ORACLE(\}|__);'"${PULL_ORACLE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)ORACLE_INGRESS(\}|__);'"${ORACLE_INGRESS}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)ORACLE_DOCKER_IMAGE(\}|__);'"${ORACLE_DOCKER_IMAGE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)GUARDIAN_QUEUE(\}|__);'"${GUARDIAN_QUEUE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)GUARDIAN_ORACLE(\}|__);'"${GUARDIAN_ORACLE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)GUARDIAN_INGRESS(\}|__);'"${GUARDIAN_INGRESS}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)GUARDIAN_DOCKER_IMAGE(\}|__);'"${GUARDIAN_DOCKER_IMAGE}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)GATEWAY_INGRESS(\}|__);'"${GATEWAY_INGRESS}"';g' "${tmp_helm_file}"
  sed -E -i 's;(__|\$\{)GATEWAY_DOCKER_IMAGE(\}|__);'"${GATEWAY_DOCKER_IMAGE}"';g' "${tmp_helm_file}"
}
