function load_vars() {
  local tmp_helm_file="${1}"
  sed -i 's;(__|{)EMAIL(}|__);'"${EMAIL}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)IP4(}|__);'"${IP4}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)IP6(}|__);'"${IP6}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)PAYER_SECRET_KEY(}|__);'"${PAYER_SECRET_KEY}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)INFISICAL_SECRET_KEY(}|__);'"${INFISICAL_SECRET_KEY}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)INFISICAL_SECRET_PATH(}|__);'"${INFISICAL_SECRET_PATH}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)INFISICAL_SECRET_SLUG(}|__);'"${INFISICAL_SECRET_SLUG}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)INFISICAL_TOKEN_NS(}|__);'"${INFISICAL_TOKEN_NS}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)NAMESPACE(}|__);'"${NAMESPACE}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)NETWORK(}|__);'"${NETWORK}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)CLUSTER_DOMAIN(}|__);'"${CLUSTER_DOMAIN}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)PULL_ORACLE(}|__);'"${PULL_ORACLE}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)PULL_QUEUE(}|__);'"${PULL_QUEUE}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)GUARDIAN_QUEUE(}|__);'"${GUARDIAN_QUEUE}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)GUARDIAN_ORACLE(}|__);'"${GUARDIAN_ORACLE}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)RPC_URL(}|__);'"${RPC_URL}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)WSS_URL(}|__);'"${WSS_URL}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)DOCKER_IMAGE(}|__);'"${DOCKER_IMAGE}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)GATEWAY_INGRESS(}|__);'"${GATEWAY_INGRESS}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)GUARDIAN_INGRESS(}|__);'"${GUARDIAN_INGRESS}"';g' "${tmp_helm_file}"
  sed -i 's;(__|{)ORACLE_INGRESS(}|__);'"${ORACLE_INGRESS}"';g' "${tmp_helm_file}"
}
