{{ if $.Values.googleApplicationCredentials }}
apiVersion: v1
kind: Secret
type: Opaque 
metadata:
  name: {{ .Values.appType}}-service-account
data:
  gcp-sa.json: {{ .Values.serviceAccountJson }}
{{ end }}
